# Generated by Django 5.1.3 on 2024-12-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concerns',
            options={'verbose_name_plural': 'Skin Concerns'},
        ),
    ]
