# Generated by Django 5.1.3 on 2024-12-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_skintype_product_skin_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
