# Generated by Django 5.1.3 on 2024-12-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_how_to_use_product_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='key_ingredients',
        ),
    ]
