# Generated by Django 5.1.3 on 2024-12-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_ingredients_product_key_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
