# Generated by Django 5.1.4 on 2025-01-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
