# Generated by Django 5.1.4 on 2025-01-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_key_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Key Ingredients',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='key_ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.keyingredient'),
        ),
    ]
